### ISSUE TITLE
Feature Request: Dock usb mouse support

### ISSUE THREAD

**Issue by JoshThibado** [agg23/openfpga-SNES#100] opened 2024-05-26 03:39 UTC
With some recent updates to openfpga, it is now possible to use a usb mouse with the analogue pocket in the docked mode. While using the gamepad is a great solution for travel, I think a lot of folks would find value in being able to use a physical mouse for snes games which support the snes mouse.

**Comment by agg23** [comment] 2024-05-26 03:46
Duplicate of #79. I need to look into this.

**Closed by agg23** 2024-05-26 03:46 UTC
